import type { InputHTMLAttributes } from 'react';

export const DEFAULT_STORES = [
  // Japanese Fashion
  'isetan',
  'takashimaya',
  'beams',
  'united arrows',
  'ships',
  'journal standard',
  'nano universe',
  'tomorrowland',
  'beauty youth',
  'studious',
  'urban research',
  'comme des garcons',
  'issey miyake',
  
  // Korean Fashion
  'musinsa',
  'w concept',
  'aland',
  'style nanda',
  'kolon',
  'beanpole',
  'sjyp',
  'wooyoungmi',
  '8seconds',
  'beyond closet',
  'ader error',
  'low classic',
  'juun j',
  
  // Global Basics
  'uniqlo',
  'muji',
  
  // Indian Fashion
  'myntra',
  'ajio',
  'nykaa fashion',
  'reliance trends',
  'fabindia',
  'lifestyle',
  'shoppers stop',
  'pantaloons',
  'max fashion',
  'westside',
  'manyavar',
  'w for woman',
  'global desi',
  'allen solly',
  'peter england',
  'van heusen',
  'louis philippe',
  'raymond',
  'blackberrys',
  
  // Middle Eastern Fashion
  'namshi',
  'ounass',
  'noon',
  'the modist',
  'boutique 1',
  'sivvi',
  'symphony',
  'splash',
  'landmark group',
  'babyshop',
  'centrepoint',
  'paris gallery',
  
  // South American & African Fashion
  'renner',
  'c&a',
  'riachuelo',
  'falabella',
  'ripley',
  'saga falabella',
  'linio',
  'dafiti',
  'woolworths sa',
  'foschini',
  'mr price',
  'ackermans',
  'pep',
  'edgars',
  'jet',
  'zando',
  'jumia',
  'superbalist',
  
  // Scandinavian Fashion
  'filippa k',
  'tiger of sweden',
  'samsoe samsoe',
  'norse projects',
  'han kjobenhavn',
  'wood wood',
  'ganni',
  'by malene birger',
  'nn07',
  'selected homme',
  'selected femme',
  'j lindeberg',
  'acne studios',
  'cos',
  'arket',
  '& other stories',
  
  // Sustainable & Ethical Fashion
  'reformation',
  'everlane',
  'veja',
  'girlfriend collective',
  'thought clothing',
  'people tree',
  'mud jeans',
  'ninety percent',
  'outerknown',
  'kotn',
  'nagnata',
  'mara hoffman',
  'mother of pearl',
  'stella mccartney',
  'patagonia',
  
  // Plus Size Fashion
  'eloquii',
  'torrid',
  'fashion to figure',
  'universal standard',
  'dia & co',
  'city chic',
  'navabi',
  'yours clothing',
  'simply be',
  'ulla popken',
  'woman within',
  'onestopplus',
  'lane bryant',
  'ashley stewart',
  'avenue',
  
  // Athletic & Activewear
  'gymshark',
  'ryderwear',
  'fabletics',
  'outdoor voices',
  'vuori',
  'rhone',
  'beyond yoga',
  'pe nation',
  'carbon38',
  'varley',
  'nobull',
  'ten thousand',
  'alphalete',
  'muscle nation',
  'echt',
  'lululemon',
  'sweaty betty',
  'under armour',
  'nike',
  'adidas',
  
  // Denim Specialists
  'nudie jeans',
  'g star raw',
  'true religion',
  'diesel',
  'ag jeans',
  'frame denim',
  'mavi',
  'nydj',
  'lucky brand',
  'dl1961',
  'paige',
  'joes jeans',
  'citizens of humanity',
  '7 for all mankind',
  'hudson jeans',
  'levis',
  'wrangler',
  'lee',
  
  // Footwear Retailers
  'aldo',
  'dsw',
  'famous footwear',
  'payless',
  'journeys',
  'clarks',
  'steve madden',
  'ecco',
  'geox',
  'blundstone',
  'rm williams',
  'christian louboutin',
  'manolo blahnik',
  'stuart weitzman',
  'tamara mellon',
  'jimmy choo',
  'nicholas kirkwood',
  'dr martens',
  'teva',
  'ugg',
  'cole haan',
  'sperry',
  'merrell',
  'keen',
  'skechers',
  'crocs',
  'rothys',
  
  // Direct to Consumer Brands
  'third love',
  'thirdlove',
  'glossier',
  'away luggage',
  'mejuri',
  'cuyana',
  'mgemi',
  'ministry of supply',
  'wolf and shepherd',
  'frank and oak',
  'quince',
  'buck mason',
  'italic',
  'koio',
  'taylor stitch',
  'mizzen main',
  'stance',
  
  // International Luxury Department Stores
  'holt renfrew',
  'galeries lafayette',
  'tsum',
  'tsvetnoy',
  'beymen',
  'sanahunt',
  'skp beijing',
  'shinsegae',
  'hyundai department store',
  'lane crawford',
  'harvey nichols',
  'harrods',
  'selfridges',
  'printemps',
  'la rinascente',
  'kadewe',
  'el corte ingles',
  
  // French Luxury & Haute Couture
  'dior',
  'christian dior',
  'dior homme',
  'hermes',
  'ysl',
  'yves saint laurent',
  'saint laurent paris',
  'nina ricci',
  'house of worth',
  'vionnet',
  'roland mouret',
  'stephane rolland',
  'charvet',
  'charvet place vendome',
  
  // French Contemporary & Premium
  'apc',
  'a.p.c.',
  'sandro',
  'sandro paris',
  'maje',
  'the kooples',
  'isabel marant',
  'kenzo',
  'paule ka',
  'cacharel',
  'cerruti',
  'cerruti 1881',
  'maison margiela',
  'margiela',
  'moncler',
  'anne fontaine',
  'alain figaret',
  'morgan',
  'kookai',
  'marithe francois girbaud',
  'girbaud',
  'armand thiery',
  'jules',
  'kiabi',
  'caroll',
  'naf naf',
  'etam',
  'comptoir des cotonniers',
  'ba&sh',
  'bash',
  'ba sh',
  'ba and sh',
  'petit bateau',
  'jennyfer',
  'bizzbee',
  'brice',
  'celio',
  'devred',
  'devred 1902',
  
  // French Casual & Sportswear
  'le coq sportif',
  'aigle',
  'airness',
  'decathlon',
  'salomon',
  'rossignol',
  'skis rossignol',
  'oxbow',
  'venum',
  'kickers',
  'promod',
  'pimkie',
  'camaieu',
  'damart',
  'montagut',
  'vilebrequin',
  'guy cotten',
  
  // French Lingerie & Intimates
  'chantelle',
  'groupe chantelle',
  'lise charmel',
  'gerbe lingerie',
  'irfe',
  'jours apres lunes',
  
  // Major Global E-commerce & Marketplaces
  'zalando',
  'asos',
  'amazon',
  'farfetch',
  'mytheresa',
  'net-a-porter',
  'matchesfashion',
  'ssense',
  'nordstrom',
  'shopbop',
  'luisaviaroma',
  'yoox',
  'the outnet',
  'alibaba',
  'aliexpress',
  'ebay',
  'walmart',
  'target',
  'macys',
  'rakuten',
  'wayfair',
  'etsy',
  'zappos',
  'shopee',
  
  // Global Fashion Brands
  'ralph lauren',
  'polo ralph lauren',
  'tommy hilfiger',
  'calvin klein',
  'hugo boss',
  'puma',
  'gap',
  'banana republic',
  'old navy',
  'coach',
  'michael kors',
  'kate spade',
  'tory burch',
  'marc jacobs',
  'brooks brothers',
  'timberland',
  'columbia sportswear',
  'vans',
  'converse',
  'tommy bahama',
  'vineyard vines',
  'peter millar',
  'southern tide',
  'robert graham',
  'greg norman',
  'greg norman collection',
  
  // US Department Stores & Major Retailers
  'nordstrom rack',
  'bloomingdales',
  'saks fifth avenue',
  'saks off 5th',
  'neiman marcus',
  'bergdorf goodman',
  'dillards',
  'belk',
  'kohls',
  'jcpenney',
  'barneys',
  'barneys new york',
  'lord taylor',
  'boscovs',
  'bon ton',
  'carson pirie scott',
  'filenes',
  'foleys',
  'kaufmanns',
  'lazarus',
  'marshall field',
  
  // Fashion & Apparel Chains
  'abercrombie',
  'abercrombie fitch',
  'american eagle',
  'aeropostale',
  'anthropologie',
  'bcbg',
  'bcbgmaxazria',
  'bonobos',
  'buckle',
  'charlotte russe',
  'chicos',
  'express',
  'forever 21',
  'free people',
  'guess',
  'hot topic',
  'j crew',
  'jcrew',
  'johnston murphy',
  'jos a bank',
  'limited',
  'madewell',
  'new york company',
  'ny&co',
  'eddie bauer',
  'eileen fisher',
  'fashion nova',
  'fredricks hollywood',
  
  // Classic & Business Wear
  'charles tyrwhitt',
  'tm lewin',
  'hawes curtis',
  'paul fredrick',
  'proper cloth',
  'indochino',
  'suit supply',
  'suitsupply',
  'mens wearhouse',
  'thomas pink',
  'hickey freeman',
  
  // Western & Outdoor Specialty
  'ariat',
  'boot barn',
  'cavenders',
  'sheplers',
  'country outfitter',
  'tractor supply',
  'atwoods',
  'murdochs',
  'buckaroo western wear',
  'western wear',
  'justin boots',
  'lucchese',
  'dan post',
  'rocky boots',
  'rods western',
  'pfi western',
  'corral boots',
  
  // Sports & Outdoor Retailers
  'dicks sporting goods',
  'dicks',
  'academy sports',
  'big 5',
  'dunhams',
  'garts',
  'oshmans',
  'moosejaw',
  'rei',
  'bass pro',
  'cabelas',
  'sportsmans warehouse',
  'outdoor research',
  'marmot',
  'campmor',
  'fleet feet',
  'badmania',
  'yonex',
  'ashaway',
  'VICTOR',
  'li ning badminton',
  'kawasaki badminton',
  'wilson',
  'head',
  'babolat',
  'prince tennis',
  'dunlop sport',
  'tecnifibre',
  'prokennex',
  'black knight',
  'apacs',
  'fleet',
  'forza badminton',
  'carlton sports',
  'yang yang',
  'butterfly table tennis',
  'donic',
  'stiga table tennis',
  'xiom',
  'joola',
  'nittaku',
  'tibhar',
  'yasaka',
  'double happiness',
  'dhs table tennis',
  'kettler',
  'karakal',
  'harrow sports',
  'eye rackets',
  'salming',
  'tennis warehouse',
  'tennis express',
  'tennis point',
  'midwest sports',
  'do it tennis',
  'tennis giant',
  'racquet science',
  'badminton warehouse',
  'direct badminton',
  'yumo pro shop',
  'tabletennis11',
  'megaspin',
  'paddle palace',
  'tabletennis store',
  'squash gear',
  'squash source',
  'control the t sports',
  'racquetball warehouse',
  'sports direct racquet',
  'butterfly',
  'mizuno',
  'artengo',
  'perfly',
  'intersport',
  'sport 2000',
  'footjoy',
  'tourna',
  'volkl tennis',
  'gamma sports',
  'solinco',
  'gosen',
  'toalson',
  'pacific',
  'mantis',
  'luxilon',
  'kirschbaum',
  'weiss cannon',
  'stringking',
  'pointfore',
  'oliver squash',
  'dunlop',
  'cornilleau',
  'ea7',
  'hang ten',
  'k2',
  'sergio tacchini',
  'freelift',
  'assn',
  'armani',
  'bovet',
  'canterburry',
  'hydrogen',
  'marco polo',
  'playbrave',
  'teamnike',
  'lecoq',
  'stiga',
  'décathlon',
  'tacchini',
  'uniglo',
  'lauren',
  'sportkind',
  'stan smith',
  'uspa',
  'vermelho',
  'mario',
  'casablanca ',
  'casa blanca',
  'nikecourt',





  
  // Specialty & Youth Fashion
  'alo yoga',
  'american apparel',
  'duluth trading',
  'dressbarn',
  'gilly hicks',
  'johnny cupcakes',
  'karmaloop',
  'kith',
  'life is good',
  'lularoe',
  'madhappy',
  'noah',
  'oaklandish',
  
  // Sports Team Stores
  'west ham',
  'west ham united',
  'whu',
  'hammers shop',
  'manchester united',
  'man utd',
  'man united',
  'mufc',
  'liverpool',
  'lfc',
  'arsenal',
  'afc',
  'chelsea',
  'cfc',
  'manchester city',
  'man city',
  'mcfc',
  'tottenham',
  'spurs',
  'thfc',
  'everton',
  'efc',
  'newcastle united',
  'nufc',
  'leeds united',
  'lufc',
  'aston villa',
  'avfc',
  'kitbag',
  'soccer store',
  
  // MLS Team Stores
  'los angeles fc',
  'lafc',
  'la galaxy',
  'galaxy',
  'seattle sounders',
  'sounders fc',
  'portland timbers',
  'timbers',
  'atlanta united',
  'atlanta utd',
  'new york city fc',
  'nycfc',
  'new york red bulls',
  'ny red bulls',
  'toronto fc',
  'tfc',
  'montreal cf',
  'cf montreal',
  'vancouver whitecaps',
  'whitecaps fc',
  'orlando city',
  'orlando city sc',
  'inter miami',
  'inter miami cf',
  'austin fc',
  'fc cincinnati',
  'columbus crew',
  'fc dallas',
  'houston dynamo',
  'sporting kansas city',
  'sporting kc',
  'colorado rapids',
  'real salt lake',
  'rsl',
  'san jose earthquakes',
  'quakes',
  'nashville sc',
  'nashville',
  'minnesota united',
  'minnesota utd',
  'philadelphia union',
  'dc united',
  'new england revolution',
  'chicago fire',
  'cf97',
  
  // NFL Team Stores
  'kansas city chiefs',
  'chiefs',
  'san francisco 49ers',
  '49ers',
  'baltimore ravens',
  'ravens',
  'buffalo bills',
  'bills',
  'cincinnati bengals',
  'bengals',
  'cleveland browns',
  'browns',
  'houston texans',
  'texans',
  'jacksonville jaguars',
  'jaguars',
  'indianapolis colts',
  'colts',
  'tennessee titans',
  'titans',
  'los angeles chargers',
  'la chargers',
  'denver broncos',
  'broncos',
  'las vegas raiders',
  'raiders',
  'new york giants',
  'giants',
  'washington commanders',
  'commanders',
  'minnesota vikings',
  'vikings',
  'detroit lions',
  'lions',
  'chicago bears',
  'bears',
  'atlanta falcons',
  'falcons',
  'new orleans saints',
  'saints',
  'tampa bay buccaneers',
  'buccaneers',
  'bucs',
  'carolina panthers',
  'panthers',
  'los angeles rams',
  'la rams',
  'seattle seahawks',
  'seahawks',
  'arizona cardinals',
  'cardinals',
  
  // European Football Team Stores
  'barcelona',
  'fc barcelona',
  'barca',
  'real madrid',
  'atletico madrid',
  'atletico',
  'bayern munich',
  'bayern',
  'borussia dortmund',
  'bvb',
  'rb leipzig',
  'leipzig',
  'paris saint germain',
  'psg',
  'olympique lyonnais',
  'lyon',
  'olympique marseille',
  'marseille',
  'ac milan',
  'milan',
  'inter milan',
  'inter',
  'juventus',
  'juve',
  'napoli',
  'as roma',
  'roma',
  'lazio',
  'ajax',
  'psv',
  'psv eindhoven',
  'feyenoord',
  'fc porto',
  'porto',
  'benfica',
  'sporting cp',
  'sporting',
  'celtic',
  'rangers',
  'galatasaray',
  'gala',
  'fenerbahce',
  'fener',
  'besiktas',
  'bjk',
  
  // Asian Retailers
  'yesstyle',
  'shein',
  'taobao',
  'tmall',
  'lazada',
  'tokopedia',
  '11street',
  'gmarket',
  'qoo10',
  
  // UK & European Department Stores
  'marks spencer',
  'marks and spencer',
  'm&s',
  'john lewis',
  'debenhams',
  'house of fraser',
  'liberty london',
  'fenwick',
  'tk maxx',
  'next',
  'matalan',
  'primark',
  'sports direct',
  'argos',
  'very',
  'littlewoods',
  
  // UK & European Fashion Retailers
  'gant',
  'reiss',
  'ted baker',
  'whistles',
  'hobbs',
  'jigsaw',
  'karen millen',
  'mint velvet',
  'joules',
  'crew clothing',
  'white stuff',
  'fatface',
  'superdry',
  'jack wills',
  'river island',
  'topshop',
  'topman',
  'new look',
  'quiz clothing',
  'end clothing',
  'mr porter',
  'browns fashion',
  'flannels',
  'boohoo',
  'booho',
  'boo hoo',
  'boohoo man',
  'boohoowoman',
  'prettylittlething',
  'plt',
  'pretty little thing',
  'missguided',
  'misguided',
  'nasty gal',
  'nastygal',
  'oliver bonas',
  'monsoon',
  'oasis fashion',
  'warehouse fashion',
  'dorothy perkins',
  'burton',
  'sosandar',
  'hush homewear',
  'boden',
  'toast clothing',
  'seasalt cornwall',
  'french connection',
  'fcuk',
  'jaeger',
  'great plains',
  'ghost london',
  'me+em',
  'me and em',
  'meem',
  'rixo london',
  'kitri studio',
  'omnes clothing',
  'never fully dressed',
  'needle and thread',
  'needle & thread',
  'finery london',
  'wyse london',
  'hope fashion',
  'brora cashmere',
  'celtic & co',
  'celtic and co',
  'pure collection',
  'damsel in a dress',
  'l.k.bennett',
  'lk bennett',
  'laura ashley',
  'planet fashion',
  'kaliko fashion',
  'precis petite',
  'windsmoor',
  'jacques vert',
  'eastex fashion',
  'alexon fashion',
  'ann harvey',
  'minuet petite',
  'country casuals',
  'berkertex',
  'boss',
  'hugo',
  'frankie say',
  'frankie says',
  'frankie says relax',
  'ben sherman',
  'ben sherman originals',
  'vivienne westwood',
  'vivienne westwood anglomania',
  'ax paris',
  'ax paris curve',
  'ax paris petite',
  
  // European Luxury & Premium
  'boozt',
  'breuninger',
  'peek cloppenburg',
  'rinascente',
  'stockmann',
  'illum',
  'magasin',
  'bijenkorf',
  'kaufhof',
  'karstadt',
  'bon marche',
  'fnac',
  
  // Australian & NZ Retailers
  'david jones',
  'myer',
  'the iconic',
  'rebel sport',
  'cotton on',
  'country road',
  'witchery',
  'the warehouse',
  'farmers',
  
  // Canadian Retailers
  'hudson bay',
  'hudsons bay',
  'canadian tire',
  'sport chek',
  'roots',
  'simons',
  'la maison simons',
  'winners',
  'marks',
  
  // High Street & Fast Fashion
  'zara',
  'von dutch',
  'h&m',
  'h and m',
  'hennes & mauritz',
  'hennes and mauritz',
  'mango',
  'bershka',
  'pull bear',
  'massimo dutti',
  'stradivarius',
  'weekday',
  'monki',
  'other stories',
  'hollister',
  
  // Sports & Outdoor
  'foot locker',
  'jd sports',
  'size',
  'snipes',
  'office',
  'schuh',
  'go outdoors',
  'cotswold outdoor',
  'mountain warehouse',
  'blacks',
  'millets',
  'ultimate outdoors',
  
  // Premium & Contemporary
  'bash',
  'zadig voltaire',
  'theory',
  'joseph',
  'all saints',
  'russell bromley',
  'kurt geiger',
  'club monaco',
  
  // Luxury Brands
  'fendi',
  'gucci',
  'prada',
  'louis vuitton',
  'louisvuitton',
  'balenciaga',
  'bottega veneta',
  'burberry',
  'versace',
  'versachi',
  'valentino',
  'dolce gabbana',
  'alexander mcqueen',
  'givenchy',
  'loewe',
  'celine',
  'chanel',
  'channel',
  'cartier',
  'tiffany',
  'omega',
  'rolex',
  'tag heuer',
  'tagheuer',
  'bulgari',
  'bvlgari',
  
  // Contemporary & Streetwear
  'stone island',
  'off white',
  'palm angels',
  'amiri',
  'fear of god',
  'ami paris',
  'rick owens',
  'thom browne',
  'jil sander',
  'jacquemus',
  'lemaire',
  'supreme',
  'bape',
  'stussy',
  'palace',
  'neighborhood',
  'wtaps',
  
  // Casual & Workwear
  'carhartt',
  'dickies',
  'champion',
  'the north face',
  'tnf',
  'new balance',
  'reebok',
  'asics',
  'fila',
  'ellesse',
  'kappa',
  'napapijri',
  'fred perry',
  'helly hansen',
  'fjallraven',
  'mammut',
  'walls',
  'key apparel',
  
  // UK Supermarket Fashion
  'asda',
  'asda george',
  'george at asda',
  'sainsburys',
  'sainsburys tu',
  'tu clothing',
  'tesco',
  'tesco f&f',
  'florence and fred',
  'peacocks',
  
  // Historical UK Retailers
  'arcadia group',
  'biba',
  'dunn co',
  'faith shoes',
  'fifty shilling tailors',
  'john collier',
  'principles',
  'richard shops',
  'mk one',
  'republic',
  'store twenty one',
  'tie rack',
  
  // Eastern European Fashion
  'reserved',
  'cropp',
  'mohito',
  'wildberries',
  'lamoda',
  'ccc shoes',
  'ochnik',
  'medicine',
  'tatuum',
  'diverse',
  
  // Chinese & Taiwanese Fashion
  'li ning',
  'lining',
  'anta sports',
  'anta',
  'semir',
  'peacebird',
  'urban revivo',
  'ochirly',
  'belle',
  'mlb china',
  'cabbeen',
  'jeanswest',
  'septwolves',
  'marisfrolg',
  'joeone',
  'cornilleau',
 
  // Mexican & Latin American Fashion
  'oggi jeans',
  'cuidado con el perro',
  'squalo',
  'sexy jeans',
  'shasa',
  'almacenes exito',
  'jumbo argentina',
  'coppel',
  'suburbia',
  
  // Southeast Asian Fashion
  'pomelo fashion',
  'love bonito',
  'rabeanco',
  'padini',
  'bench',
  'penshoppe',
  'greyhound',
  'jaspal',
  'cps chaps',
  'g2000',
  
  // Turkish & Middle Eastern Fashion
  'lc waikiki',
  'defacto',
  'ipekyol',
  'network',
  'machka',
  'hotic',
  'penti',
  'roman',
  'flo',
  'mudo',
  
  // German & Central European Fashion
  'soliver',
  's oliver',
  'tom tailor',
  'gerry weber',
  'orsay',
  'deichmann',
  'takko fashion',
  'bonprix',
  'hallhuber',
  'betty barclay',
  
  // Italian Fashion Retailers
  'ovs',
  'calzedonia',
  'intimissimi',
  'tezenis',
  'upim',
  'carpisa',
  'yamamay',
  'fiorella rubino',
  'imperial fashion',
  'piazza italia',
  'antony morato',
  
  // Spanish & Portuguese Fashion
  'springfield',
  'womensecret',
  'cortefiel',
  'adolfo dominguez',
  'bimba y lola',
  'mayoral',
  'gocco',
  'panama jack',
  'sfera',
  'trucco',
  
  // Vintage & Second-hand
  'vestiaire collective',
  'depop',
  'thredup',
  'the realreal',
  'rebag',
  'round two',
  'kilogarm',
  'think twice',
  'pop boutique',
  'melia vintage',
  
  // Children's & Maternity Wear
  'carters',
  'oshkosh bgosh',
  'oshkosh',
  'gymboree',
  'janie and jack',
  'hanna andersson',
  'jacadi',
  'bonpoint',
  'sergent major',
  'il gufo',
  'chicco',
  'jojo maman bebe',
  
  // Workwear & Uniforms
  'cintas',
  'aramark',
  'bulwark fr',
  'mascot workwear',
  'snickers workwear',
  'engelbert strauss',
  'fristads kansas',
  'chef works',
  'landau scrubs',
  'figs',
  
  // Outdoor & Tactical Wear
  'klattermusen',
  'houdini sportswear',
  'sherpa adventure gear',
  'montane',
  'sitka gear',
  'harkila',
  'first lite',
  'kuiu',
  'helikon tex',
  'uf pro',
  'arc teryx',
  
  // Specialty Undergarments & Swimwear
  'agent provocateur',
  'fleur du mal',
  'journelle',
  'panache',
  'curvy kate',
  'elomi',
  'simone perele',
  'cuup',
  'tomboyx',
  'speedo',
  'arena',
  'gottex',
  'orlebar brown',
  'andie swim',
  'victorias secret',
  'la perla',
  'triumph',
  
  // Digital Native Brands
  'asket',
  'son of a tailor',
  'black lapel',
  'dagne dover',
  'aurate',
  'soko',
  'baboon to the moon',
  'monos',
  'western rise',
  'duer',
  'away',
  'allbirds',
  
  // British Heritage & Outerwear Brands
  'belstaff',
  'barbour',
  'barbour international',
  'cp company',
  'c.p. company',
  'c.p company',
  'cord',
  'cordings',
  'cordings of piccadilly',
  'hunter',
  'hunter boots',
  'dubarry',
  'mackintosh',
  'aquascutum',
  'grenfell',
  'peregrine',
  'private white v.c.',
  'albam',
  'sunspel',
  'john smedley',
  'hackett',
  'musto',
  'henri lloyd',
  'schoffel',
  'paul smith',
  'paul smith london',
  'ps paul smith',
  'cotton traders',
  'oliver sweeney',
  'turnbull & asser',
  'drakes',
  'drakes london',
  'edward green',
  'john lobb',
  'trickers',
  'crockett & jones',
  'churchs',
  'churches shoes',
  'loake',
  'oliver spencer',
  'nigel cabourn',
  'universal works',
  'margaret howell',
  'folk clothing',
  'albam clothing',
  'percival',
  'community clothing',
  'blackhorse lane',
  'lyle scott',
  'lyle & scott',
  'lyle and scott',
  'lylle and scott',
  'passenger clothing',
  'passenger',

  // Denim & Workwear 
  'levis vintage clothing',
  'lvc',
  'levis made & crafted',
  'lee cooper',
  'lee jeans',
  'replay',
  'prps',
  'raw denim',
  'selvedge denim',
  'iron heart',
  'momotaro',
  'edwin',
  'nudie',

  // Ralph Lauren Brands
  'purple label',
  'rrl',
  'double rl',
  'ralph lauren purple label',
  'polo sport',
  'chaps',
  'lauren ralph lauren',
  'polo golf',
  'ralph lauren home',
  'ralph lauren collection'
];

export const ACCEPTED_FILE_TYPES = ['.xlsx', '.xls', '.csv'] as const;
export const COLUMNS_TO_EXCLUDE = [
  // CPC Columns (Multiple Currencies)
  'CPC (USD)', 'CPC', 'Cost Per Click (USD)', 'Cost Per Click',
  'CPC (EUR)', 'Cost Per Click (EUR)',
  'CPC (GBP)', 'Cost Per Click (GBP)',
  'CPC (AUD)', 'Cost Per Click (AUD)',
  'CPC (CAD)', 'Cost Per Click (CAD)',
  'CPC (JPY)', 'Cost Per Click (JPY)',
  'CPC (CNY)', 'Cost Per Click (CNY)',
  'CPC (INR)', 'Cost Per Click (INR)',
  
  // SERP Columns
  'SERP Features', 'SERP',
  
  // Difficulty Columns
  'Keyword Difficulty', 'KD', 'Difficulty', 'Keyword Difficulty (%)',
  
  // Competition Columns  
  'Competition', 'Competitive Density'
];
export const DEFAULT_MIN_VOLUME = 100;

export const LARGE_FILE_THRESHOLD = 10 * 1024 * 1024; // 10MB threshold

export interface FileData {
  id: string;
  originalData: FilteredDataRow[];
  filteredData: FilteredDataRow[];
  fileName: string;
  sheetName: string;
  originalRows: number;
  filteredRows: number;
  storeFilteredRows: number;
  volumeFilteredRows: number;
  customStoreFilteredRows: number;
}

export interface FilteredDataRow {
  Keyword: string;
  Position?: string | number;  // Made optional
  Volume: number;
  Type?: string;              // Made optional
  Intent?: string;            // Already optional
  URL?: string;               // Add the URL field as optional
}

export interface ExtendedInputProps extends InputHTMLAttributes<HTMLInputElement> {
  webkitdirectory?: string;
  directory?: string;
}

// Define column configurations for each tool
export const KSUG_FORMATTER_COLUMNS = ['Keyword', 'Intent', 'Volume'] as string[];
export const KW_RELEVANCY_COLUMNS = ['Keyword', 'Position', 'Volume', 'Type', 'URL'] as string[]; 